# Generated by Django 5.0.2 on 2024-02-24 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcreate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 24, 11, 34, 6, 174267, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
